### ISSUE TITLE
Witch license do you use ?

### ISSUE THREAD

**Issue by grobx** [deib-polimi/TRex#3]
Hi, I would like to know witch license do you use for this project.
Thanks.

**Comment by dippi** [comment]
The license is usually specified at the beginning of each source file.
For the library is LGPLv3 and for the server is GPLv3; where not explicitly stated assume GPLv3.

By the way I added few lines of explanation in the README file.

**Comment by KrishnaPG** [comment]
Wondering if it would be possible to consider switching to a more permissive licence, such as MIT, BSD or Apache - which would enable more people to contribute to (and use) this without inhibition.

**Comment by cugola** [comment]
Sorry, but I think LGPL for the "core" of the tool and GPL for the other parts is a reasonable choice. Having said that, if you have specific needs we can discuss them. In that case, drop me a direct message.
